version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rate-app
    container_name: rate-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./vendor:/var/www/vendor
    ports:
      - "8000:9000"
    networks:
      - app-network
    depends_on:
      - db
    entrypoint: >
      sh -c "composer install &&
            php artisan migrate &&
            php-fpm"
  db:
    image: mysql:8.0
    container_name: rate-app
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rate-app
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
